install.packages("devtools")
library(devtools)
install_github("andrewzm/STRbook")
install_version("ggplot2", version = "3.0.0", repos = "http://cran.us.r-project.org")
install_version("animation", version = "2.5", repos = "https://cran.us.r-project.org")
install_version("ape", version = "5.1", repos = "https://cran.us.r-project.org")
install_version("broom", version = "0.5.0", repos = "https://cran.us.r-project.org")
install.packages("fda")
install_version("CCA", version = "1.2", repos = "https://cran.us.r-project.org")
install_version("EFDR", version = "0.1.1", repos = "https://cran.us.r-project.org")
install_version("expm", version = "0.999-2", repos = "https://cran.us.r-project.org")
install_version("fields", version = "9.6", repos = "https://cran.us.r-project.org")
install.packages("latticeExtra")
install_version("FRK", version = "0.2.2.1", repos = "http://cran.us.r-project.org")
install_version("ggmap", version = "2.6.1", repos = "https://cran.us.r-project.org")
install_version("ggquiver", version = "0.1.0", repos = "https://cran.us.r-project.org")
install.packages("ggvis")
install.packages("grid")
install_version("gridExtra", version = "2.3", repos = "https://cran.us.r-project.org")
install_version("gstat", version = "1.1-6", repos = "https://cran.us.r-project.org")
install_version("IDE", version = "0.3.0", repos = "http://cran.us.r-project.org")
#install_version("INLA", version = "18.07.12", repos = "https://inla.r-inla-download.org/R/stable/")
install.packages("splancs")
install.packages("https://inla.r-inla-download.org/R/stable/src/contrib/INLA_18.07.12.tar.gz", repos=NULL, type="source")
#install.packages("IDE")
#install.packages("INLA")
install_version("lattice", version = "0.20-35", repos = "https://cran.us.r-project.org")
install_version("leaps", version = "3.0", repos = "https://cran.us.r-project.org")
install_version("lmtest", version = "0.9-36", repos = "https://cran.us.r-project.org")
install_version("maps", version = "3.3.0", repos = "https://cran.us.r-project.org")
install_version("maptools", version = "0.9-3", repos = "https://cran.us.r-project.org")
install_version("Matrix", version = "1.2-14", repos = "https://cran.us.r-project.org")
install_version("mgcv", version = "1.8-23", repos = "https://cran.us.r-project.org")
install_version("nlme", version = "3.1-131", repos = "https://cran.us.r-project.org")
install_version("plyr", version = "1.8.4", repos = "https://cran.us.r-project.org")
install_version("purrr", version = "0.2.5", repos = "https://cran.us.r-project.org")
install_version("RColorBrewer", version = "1.1-2", repos = "https://cran.us.r-project.org")
install_version("scoringRules", version = "0.9.5", repos = "https://cran.us.r-project.org")
install.packages("shiny")
install_version("sp", version = "1.3-1", repos = "https://cran.us.r-project.org")
install_version("spacetime", version = "1.2-2", repos = "https://cran.us.r-project.org")
install_version("SpatialVx", version = "0.6-3", repos = "https://cran.us.r-project.org")
install_version("SpatioTemporal", version = "1.1.7", repos = "https://cran.us.r-project.org")
install_version("SpecsVerification", version = "0.5-2", repos = "https://cran.us.r-project.org")
install_version("stargazer", version = "5.2.2", repos = "https://cran.us.r-project.org")
install_version("tidyr", version = "0.8.1", repos = "https://cran.us.r-project.org")
install_version("verification", version = "1.42", repos = "https://cran.us.r-project.org")
install_version("xtable", version = "1.8-2", repos = "https://cran.us.r-project.org")
#install_version("rlang", version = "0.3.0", repos = "https://cran.us.r-project.org")
install_version("dplyr", version = "0.7.6", repos = "https://cran.us.r-project.org")
