install.packages("devtools")
library(devtools)
install.packages("animation")
install.packages("ape")
install.packages("expm")
install.packages("fields")
install.packages("ggmap")
install.packages("gridExtra")
install.packages("gstat")
install.packages("https://inla.r-inla-download.org/R/stable/src/contrib/INLA_18.07.12.tar.gz", repos=NULL, type="source")
install.packages("lattice")
install.packages("leaps")
install.packages("lmtest")
install.packages("maps")
install.packages("Matrix")
install.packages("mgcv")
install.packages("nlme")
install.packages("plyr")
install.packages("RColorBrewer")
install.packages("scoringRules")
install.packages("shiny")
install.packages("sp")
install.packages("spacetime")
install.packages("SpatialVx")
install.packages("SpatioTemporal")
install.packages("SpecsVerification")
install.packages("stargazer")
install.packages("tidyr")
install.packages("verification")
install.packages("xtable")
install_github("andrewzm/STRbook")
install.packages("broom",)
install.packages("CCA",)
install.packages("EFDR",)
install.packages("ggquiver")
install.packages("dplyr")
install.packages("FRK")
install.packages("ggplot2")	
install.packages("maptools")
install.packages("splancs")
# update the packages to the desired version
install_version("devtools", version = "1.13.6", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
library(devtools)
install_version("broom", version = "0.5.0", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("dplyr", version = "0.7.6", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("FRK", version = "0.2.2", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("ggplot2", version = "3.0.0", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("IDE", version = "0.2.0", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("maptools", version = "0.9-3", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("nlme", version = "3.1-131", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("purrr", version = "0.2.5", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("scoringRules", version = "0.9.5", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("sp", version = "1.3-1", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("spacetime", version = "1.2-2", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("SpatialVx", version = "0.6-3", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("stargazer", version = "5.2.2", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
install_version("tidyr", version = "0.8.1", repos = "https://mirror.aarnet.edu.au/pub/CRAN/")
